let cita = "Tres tristes tigres comen trigo en un trigal";
let substring = "tigres comen trigo";
let tamanoDeCita = cita.length;
console.log("El tamaño de la cita es: %s", tamanoDeCita);
let indice = cita.indexOf(substring);
console.log("El indice del substring es: %i", indice);
let tamanoDeSubstring = substring.length;
let posicionFinIndice = indice + tamanoDeSubstring;
let citaRevisada = cita.slice(0, posicionFinIndice);
console.log(citaRevisada);
